services:
  express-app:
    image: yutharsans/express-app
    ports:
      - 8080:8080
  watchtower: 
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVEL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
