name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - uses: actions/checkout@v4

      # We need to login so we can later push the image without issues
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Builds yutharsans/express-app
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: yutharsans/express-app:latest
